// eslint-disable-next-line import/prefer-default-export
export const TRANSLATIONS = {
  en_US: {
    'Login.LogIn': 'Log In',
    'Login.SeleteLanguage': 'Select Language',
    'Login.MyHouse': 'HomeKasa',
    'Login.ForgetPassword': 'Forget Password?',
    'Login.DontHaveAnAccount': "Don't Have An Account?",
    'Login.RememberMe': 'Remember me',
    'Login.EmailAddress': 'Email Address',
    'Login.Password': 'Password',
    'Signup.MyHouse': 'HomeKasa',
    'Signup.SignUp': 'Sign Up',
    'Signup.UserName': 'Your Name',
    'Signup.UserEmail': 'Email',
    'Signup.Password': 'Password(at least 6 characters)',
    'Signup.CPassword': 'Confirm Password',
    'Signup.SaveInfo': 'Save User Information',
    'Signup.Already': 'Already have an account? Log In',
    'ResetPW.CurrentPW': 'Current Password',
    'ResetPW.NewPW': 'New Password',
    'ResetPW.ConfirmPW': 'Confirm Password',
    'ResetPW.Email': 'Email',
    'ResetPW.ResetPassword': 'Reset Password',
    'Sidebar.AllHouse': 'Houses',
    'Sidebar.Report': 'Report',
    'Sidebar.EditProfile': 'Edit Profile',
    'Sidebar.Logout': 'Log Out',
    'Sidebar.DemoUser': 'Demo user, changes restricted!',
    'Sidebar.ResetPassword': 'Reset Password',
    'Houselist.AddHouse': 'Add a New House',
    'HouseSummary.ViewDetail': 'View Detail',
    'HouseSummary.Name': 'Name',
    'HouseSummary.Address': 'Address',
    'HouseSummary.Status': 'Status',
    'HouseSummary.PurchasePrice': 'Purchase Price (optional)',
    'HouseSummary.CurrentPrice': 'Current Price',
    'HouseSummary.DatePurchased': 'Date Purchased (optional)',
    'HouseSummary.CityState': 'City, State',
    'HouseSummary.ZipCode': 'Zip Code',
    'Button.Add': 'Add',
    'Button.Edit': 'Edit',
    'Button.Delete': 'Delete',
    'Button.AddDocument': 'Add Document',
    'Button.ShowDocuments': 'Show Documents',
    'Button.Cancel': 'Cancel',
    'Button.Update': 'Update',
    'Button.Upload': 'Upload',
    'Button.Download': 'Download',
    'Button.Close': 'Close',
    'Button.Create': 'Create',
    'Button.ShowRenters': 'Show Renters',
    'EditUser.UpdateProfile': 'Update Profile',
    'EditUser.Name': 'Name',
    'EditUser.Email': 'Email',
    'EditUser.Password': 'Password',
    'EditUser.Language': 'Language',
    'EditUser.English': 'English',
    'EditUser.Spain': 'Spain',
    'EditUser.Currency': 'Currency',
    'AddEditHouse.AddHouse': 'Add Property',
    'AddEditHouse.EditHouse': 'Edit House',
    'AddEditHouse.Rented': 'Rented',
    'AddEditHouse.PrimaryHouse': 'Primary House',
    'HouseDetail.DetailAbout': 'Detail About',
    'HouseDetail.Mortgage': 'Mortgage',
    'HouseDetail.Insurance': 'Insurance',
    'HouseDetail.Taxes': 'Taxes',
    'HouseDetail.Lease': 'Lease',
    'HouseDetail.Renter': 'Renter',
    'Document.UploadDocument': 'Upload Document',
    'Document.Comment': 'Comment',
    'Document.File': 'File',
    'Document.ShowHouseDetail': 'Show HouseDetail Documents',
    'Document.ShowInsurace': 'Show Insurance Documents',
    'Document.ShowHouseTaxes': 'Show Taxes Documents',
    'Document.ShowHouseLease': 'Show Lease Documents',
    'Document.ShowHouseMortagage': 'Show Morgage Documents',
    'Document.Name': 'Name',
    'Document.FileSize': 'File Size',
    'Document.UploadDate': 'Upload Date',
    'Document.Action': 'Action',
    'Insurance.Comapny': 'Company',
    'Insurance.Amount': 'Amount',
    'Insurance.PolicyNumber': 'Policy Number',
    'Insurance.PhoneNumber': 'Phone Number',
    'Insurance.StartDate': 'Start Date',
    'Insurance.EndDate': 'End Date',
    'Insurance.AddInsurance': 'Add Insurance',
    'Insurance.EditInsurance': 'Edit Insurnace',
    'Insurance.DueDate': 'Due Date',
    'Insurance.DueAmount': 'Due Amount',
    'Lease.StartDate': 'Start Date',
    'Lease.EndDate': 'End Date',
    'Lease.RentDue': 'Rent Due',
    'Lease.Yearly': 'Yearly',
    'Lease.SignedOn': 'Signed On',
    'Lease.Name': 'Name',
    'Lease.AddLease': 'Add Lease',
    'Lease.EditLease': 'Edit Lease',
    'Lease.Action': 'Action',
    'Lease.RentDueDate': 'Rent Due Date',
    'Lease.RentDueAmount': 'Rent Due Amount',
    'Mortgage.Name': 'Loan Name',
    'Mortgage.Number': 'Loan Number',
    'Mortgage.PrincipalAmount': 'Original Principal Amount',
    'Mortgage.InterestRate': 'Interest Rate',
    'Mortgage.MonthlyPayment': 'Monthly Payment',
    'Mortgage.Type': 'Type',
    'Mortgage.DueDate': 'Due Date',
    'Mortgage.BankName': 'Bank Name',
    'Morgage.AddMortgage': 'Add Mortgage',
    'Morgage.EditMortgage': 'Edit Mortgage',
    'Taxes.YearlyAmount': 'Yealy Amount',
    'Taxes.ParcelNumber': 'Parcel Number',
    'Taxes.DueDate': 'Due Date',
    'Taxes.DueAmount': 'Due Amount',
    'Taxes.WebSite': 'Web Site',
    'Taxes.AddTax': 'Add Tax',
    'Taxes.EditTax': 'Edit Tax',
    'Renter.Name': 'Name',
    'Renter.Age': 'Age',
    'Renter.Phone': 'Phone',
    'Renter.Email': 'Email',
    'Renter.Employer': 'Employer',
    'Renter.Identifier': 'Identifier',
    'Renter.Lease': 'Lease',
    'Renter.RenterList': 'Renter List',
    'Renter.Actions': 'Actions',
    'Renter.NoRecords': 'No records to display',
    'Renter.Search': 'Search',
    'Renter.ShowRenters': 'Show Renters',
    'Renter.AddRenter': 'Add Renter',
    'Renter.EditRenter': 'Edit Renter',
    'Transaction.Comments': 'Commnets',
    'Transaction.Amount': 'Amount',
    'Transaction.Type': 'Type',
    'Transaction.Inflow': 'Inflow',
    'Transaction.Date': 'Date',
    'Transaction.TransactionList': 'Transaction List',
    'Transaction.Actions': 'Actions',
    'Transaction.NoRecords': 'No records to display',
    'Transaction.Search': 'Search',
    'ForgotPW.ForgotPassword': 'Forgot Password',
    'ForgotPW.Submit': 'Submit',
    'ForgotPW.UserEmail': 'User Email',
  },
  es_ES: {
    'Login.LogIn': 'Iniciar sesión',
    'Login.SeleteLanguage': 'Seleccionar idioma',
    'Login.MyHouse': 'Mi casa',
    'Login.ForgetPassword': 'Contraseña olvidada?',
    'Login.DontHaveAnAccount': 'No tengo una cuenta?',
    'Login.RememberMe': 'Recuérda me',
    'Login.EmailAddress': 'Dirección de correo electrónico',
    'Login.Password': 'Contraseña',
    'Signup.MyHouse': 'Mi casa',
    'Signup.SignUp': 'Regístrate',
    'Signup.UserName': 'Nombre de usuario',
    'Signup.UserEmail': 'Email del usuario',
    'Signup.Password': 'Contraseña (al menos 6 caracteres)',
    'Signup.CPassword': 'Confirmar contraseña',
    'Signup.SaveInfo': 'Guardar información del usuario',
    'Signup.Already': '¿Ya tienes una cuenta? Iniciar sesión',
    'ResetPW.CurrentPW': 'contraseña actual',
    'ResetPW.NewPW': 'Nueva contraseña',
    'ResetPW.confirmPW': 'Confirmar contraseña',
    'ResetPW.Email': 'Correo electrónico',
    'ResetPW.ResetPassword': 'Restablecer la contraseña',
    'Sidebar.AllHouse': 'Toda la casa',
    'Sidebar.Report': 'Reporte',
    'Sidebar.EditProfile': 'Editar perfil',
    'Sidebar.Logout': 'Cerrar sesión',
    'Sidebar.DemoUser': 'Usuario de demostración, ¡cambios restringidos!',
    'Sidebar.ResetPassword': 'Restablecer la contraseña',
    'Houselist.AddHouse': 'Agregar una casa nueva',
    'HouseSummary.ViewDetail': 'Ver Detalle',
    'HouseSummary.Name': 'Nombre',
    'HouseSummary.Address': 'Habla a',
    'HouseSummary.Statu': 'Estado',
    'HouseSummary.PurchasePrice': 'Precio de compra',
    'HouseSummary.CurrentPrice': 'Precio de compra',
    'HouseSummary.DatePurchased': 'fecha de compra',
    'HouseSummary.CityState': 'Estado de la Ciudad',
    'HouseSummary.ZipCode': 'Código postal',
    'Button.Add': 'Añadir',
    'Button.Edit': 'Editar',
    'Button.Delete': 'Eliminar',
    'Button.AddDocument': 'Agregar documento',
    'Button.ShowDocuments': 'Mostrar documentos',
    'Button.Cancel': 'Cancelar',
    'Button.Update': 'Actualizar',
    'Button.Upload': 'Subir',
    'Button.Download': 'Descargar',
    'Button.Close': 'Cerca',
    'Button.Create': 'Crear',
    'Button.ShowRenters': 'Mostrar inquilinas',
    'EditUser.UpdateProfile': 'Actualización del perfil',
    'EditUser.Name': 'Nombre',
    'EditUser.Email': 'Correo electrónico',
    'EditUser.Password': 'Contraseña',
    'EditUser.Language': 'Idioma',
    'EditUser.English': 'Inglés',
    'EditUser.Spain': 'España',
    'EditUser.Currency': 'Moneda',
    'AddEditHouse.AddHouse': 'Añadir casa',
    'AddEditHouse.EditHouse': 'Editar casa',
    'AddEditHouse.Rented': 'Alquilado',
    'AddEditHouse.PrimaryHouse': 'Casa primaria',
    'HouseDetail.DetailAbout': 'Detalle sobre',
    'HouseDetail.Mortgage': 'Hipoteca',
    'HouseDetail.Insurance': 'Seguro',
    'HouseDetail.Taxes': 'Impuestos',
    'HouseDetail.Lease': 'Arrendamiento',
    'HouseDetail.Renter': 'Inquilino',
    'Document.UploadDocument': 'Subir documento',
    'Document.Comment': 'Comentario',
    'Document.File': 'Expediente',
    'Document.ShowHouseDetail': 'Mostrar documentos de HouseDetail',
    'Document.Name': 'Nombre',
    'Document.FileSize': 'Tamaño del archivo',
    'Document.UploadDate': 'Fecha de carga',
    'Document.Action': 'Acción',
    'Insurance.Comapny': 'Empresa',
    'Insurance.Amount': 'Cantidad',
    'Insurance.PolicyNumber': 'Número de póliza',
    'Insurance.PhoneNumber': 'Número de teléfono',
    'Insurance.StartDate': 'Fecha de inicio',
    'Insurance.EndDate': 'Fecha final',
    'Insurance.AddInsurance': 'Agregar seguro',
    'Insurance.EditInsurance': 'Editar seguro',
    'Insurance.DueDate': 'Fecha de vencimiento',
    'Insurance.DueAmount': 'Cantidad debida',
    'Lease.StartDate': 'Fecha de inicio',
    'Lease.EndDate': 'Fecha final',
    'Lease.RentDue': 'Renta debida',
    'Lease.Yearly': 'Anual',
    'Lease.SignedOn': 'Firmado',
    'Lease.Name': 'Nombre',
    'Lease.AddLease': 'Añadir contrato de arrendamiento',
    'Lease.EditLease': 'Editar contrato de arrendamiento',
    'Lease.Action': 'Acción',
    'Lease.RentDueDate': 'Fecha de vencimiento del alquiler',
    'Lease.RentDueAmount': 'Monto adeudado del alquiler',
    'Mortgage.Name': 'Nombre',
    'Mortgage.Number': 'Número',
    'Mortgage.PrincipalAmount': 'Cantidad principal',
    'Mortgage.InterestRate': 'Tasa de interés',
    'Mortgage.MonthlyPayment': 'Mensualidad',
    'Mortgage.Type': 'Tipo',
    'Mortgage.DueDate': 'Fecha de vencimiento',
    'Mortgage.BankName': 'Nombre del banco',
    'Morgage.AddMortgage': 'Añadir hipoteca',
    'Morgage.EditMortgage': 'Editar hipoteca',
    'Taxes.YearlyAmount': 'Cantidad anual',
    'Taxes.ParcelNumber': 'Número de parcela',
    'Taxes.DueDate': 'Fecha de vencimiento',
    'Taxes.DueAmount': 'Cantidad debida',
    'Taxes.WebSite': 'Sitio web',
    'Taxes.AddTax': 'Agregar impuesto',
    'Taxes.EditTax': 'Editar impuesto',
    'Renter.Name': 'Nombre',
    'Renter.Age': 'Años',
    'Renter.Phone': 'Teléfono',
    'Renter.Email': 'Correo electrónico',
    'Renter.Employer': 'Empleador',
    'Renter.Identifier': 'Identificador',
    'Renter.Lease': 'Arrendamiento',
    'Renter.RenterList': 'Lista de inquilinos',
    'Renter.Actions': 'Comportamiento',
    'Renter.NoRecords': 'No hay registros que mostrar',
    'Renter.Search': 'Buscar',
    'Renter.ShowRenters': 'Mostrar inquilinas',
    'Renter.AddRenter': 'Agregar inquilino',
    'Renter.EditRenter': 'Editar inquilino',
    'Transaction.Comments': 'Comentarios',
    'Transaction.Amount': 'Cantidad',
    'Transaction.Type': 'Tipo',
    'Transaction.Inflow': 'Afluencia',
    'Transaction.Date': 'Fecha',
    'Transaction.TransactionList': 'Lista de transacciones',
    'Transaction.Actions': 'Comportamiento',
    'Transaction.NoRecords': 'No hay registros que mostrar',
    'Transaction.Search': 'Buscar',
    'ForgotPW.ForgotPassword': 'Se te olvidó tu contraseña',
    'ForgotPW.Submit': 'Enviar',
    'ForgotPW.UserEmail': 'Email del usuario',
  },
};
